version: '3.8'

services:
  trading-bot:
    build: .
    container_name: trading-bot
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./.env:/app/.env
    ports:
      - "0.0.0.0:8002:8000"  # Prometheus - acessível externamente na porta 8002
    environment:
      - TZ=${TZ}
      - PYTHONPATH=/app/src
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
      - HG_FINANCE_API_KEY=${HG_FINANCE_API_KEY}
      - BRAPI_API_KEY=${BRAPI_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - QUANDL_API_KEY=${QUANDL_API_KEY}
      - TIINGO_API_KEY=${TIINGO_API_KEY}
    networks:
      - trading-net
    restart: unless-stopped
    command: python src/backend/app.py
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "logging=promtail"

  trading-api:
    build: .
    container_name: trading-api
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./.env:/app/.env
    ports:
      - "0.0.0.0:8000:8001"  # API REST - acessível externamente na porta 8000
    environment:
      - TZ=${TZ}
      - PYTHONPATH=/app/src
      - HG_FINANCE_API_KEY=${HG_FINANCE_API_KEY}
      - BRAPI_API_KEY=${BRAPI_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - QUANDL_API_KEY=${QUANDL_API_KEY}
      - TIINGO_API_KEY=${TIINGO_API_KEY}
    networks:
      - trading-net
    restart: unless-stopped
    command: python -m uvicorn src.backend.api:app --host 0.0.0.0 --port 8001 --reload
    depends_on:
      - trading-bot
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "logging=promtail"

  trading-web:
    build: 
      context: .
      dockerfile: src/frontend/trading-web/Dockerfile
    container_name: trading-web
    ports:
      - "0.0.0.0:3000:3000"  # Frontend React - acessível externamente
    environment:
      - TZ=${TZ}
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - trading-net
    restart: unless-stopped
    depends_on:
      - trading-api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "logging=promtail"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "0.0.0.0:9090:9090"  # Prometheus UI - acessível externamente
    volumes:
      - ./src/backend/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - trading-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "logging=promtail"

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "0.0.0.0:3030:3000"  # Grafana - acessível externamente
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./src/backend/monitoring/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/trading-bot.yml:ro
      - ./src/backend/monitoring/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./src/backend/monitoring/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
    networks:
      - trading-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "logging=promtail"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "0.0.0.0:3100:3100"  # Loki - acessível externamente
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - trading-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "logging=promtail"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./src/backend/monitoring/promtail.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - trading-net
    user: root  # Necessário para acessar o socket do Docker
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "logging=promtail"

networks:
  trading-net:
    driver: bridge

volumes:
  grafana-storage:
